// packages/vue/src/DoclePlayground.vue
<template>
  <iframe
    ref="iframeRef"
    :src="iframeSrc"
    :style="{
      width: '100%',
      height: height,
      border: 'none',
      borderRadius: '8px'
    }"
    title="Docle Playground"
    sandbox="allow-scripts allow-same-origin allow-popups"
  />
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import type { DoclePlaygroundProps, DocleEmitEvents } from './types';

const props = withDefaults(defineProps<DoclePlaygroundProps>(), {
  lang: 'python',
  code: 'print("Hello, Docle!")',
  theme: 'dark',
  readonly: false,
  showOutput: true,
  autorun: false,
  height: '400px'
});

const emit = defineEmits<DocleEmitEvents>();

const iframeRef = ref<HTMLIFrameElement | null>(null);
const currentCode = ref(props.code);

// Compute iframe src URL
const iframeSrc = computed(() => {
  const baseUrl = props.endpoint || 'https://app.docle.co';
  const params = new URLSearchParams({
    lang: props.lang,
    theme: props.theme,
    code: encodeURIComponent(currentCode.value || ''),
    readonly: String(props.readonly),
    showOutput: String(props.showOutput),
    autorun: String(props.autorun)
  });

  // Add API key if provided
  if (props.apiKey) {
    params.set('apiKey', props.apiKey);
  }

  return `${baseUrl}/embed?${params.toString()}`;
});

// Handle postMessage events
const handleMessage = (event: MessageEvent) => {
  if (iframeRef.value && event.source !== iframeRef.value.contentWindow) {
    return;
  }

  const { type, data } = event.data;

  if (type === 'docle-ready') {
    // Send API key to iframe when it's ready
    if (props.apiKey) {
      iframeRef.value?.contentWindow?.postMessage({
        type: 'docle-set-apikey',
        apiKey: props.apiKey
      }, '*');
    }
    emit('ready', data);
  } else if (type === 'docle-result') {
    emit('run', data);
  } else if (type === 'docle-error') {
    emit('error', data);
  }
};

// Run code
const run = () => {
  iframeRef.value?.contentWindow?.postMessage({ type: 'docle-run' }, '*');
};

// Set code
const setCode = (newCode: string) => {
  currentCode.value = newCode;
  iframeRef.value?.contentWindow?.postMessage({ type: 'docle-set-code', code: newCode }, '*');
};

// Expose methods
defineExpose({
  run,
  setCode
});

// Watch for prop changes
watch(() => props.code, (newCode) => {
  currentCode.value = newCode || '';
});

watch(() => props.lang, (newLang) => {
  // Send language change to iframe
  iframeRef.value?.contentWindow?.postMessage({
    type: 'docle-set-lang',
    lang: newLang
  }, '*');
});

// Lifecycle
onMounted(() => {
  window.addEventListener('message', handleMessage);
});

onUnmounted(() => {
  window.removeEventListener('message', handleMessage);
});
</script>

// packages/react/src/DoclePlayground.tsx
import { useEffect, useRef, useCallback } from 'react';
import type { DoclePlaygroundProps, DocleResult } from './types';

/**
 * Embeddable code playground component
 *
 * @example
 * ```tsx
 * <DoclePlayground
 *   lang="python"
 *   code="print('Hello, World!')"
 *   onRun={(result) => console.log(result)}
 * />
 * ```
 */
export function DoclePlayground({
  lang = 'python',
  theme = 'dark',
  code = '',
  readonly = false,
  showOutput = true,
  autorun = false,
  height = '400px',
  width = '100%',
  endpoint,
  apiKey,
  onReady,
  onRun,
  onError,
  className,
  style
}: DoclePlaygroundProps) {
  const iframeRef = useRef<HTMLIFrameElement>(null);

  // Handle messages from iframe
  const handleMessage = useCallback((event: MessageEvent) => {
    // Only process messages from our iframe
    if (event.source !== iframeRef.current?.contentWindow) return;

    const { type, data } = event.data;

    switch (type) {
      case 'docle-ready':
        // Send API key to iframe when it's ready
        if (apiKey) {
          iframeRef.current?.contentWindow?.postMessage({
            type: 'docle-set-apikey',
            apiKey: apiKey
          }, '*');
        }
        onReady?.(data);
        break;
      case 'docle-result':
        onRun?.(data as DocleResult);
        break;
      case 'docle-error':
        onError?.(data);
        break;
    }
  }, [onReady, onRun, onError, apiKey]);

  useEffect(() => {
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, [handleMessage]);

  // Send language change to iframe when lang prop changes
  useEffect(() => {
    if (iframeRef.current?.contentWindow) {
      iframeRef.current.contentWindow.postMessage({
        type: 'docle-set-lang',
        lang: lang
      }, '*');
    }
  }, [lang]);

  // Send code change to iframe when code prop changes
  useEffect(() => {
    if (iframeRef.current?.contentWindow) {
      iframeRef.current.contentWindow.postMessage({
        type: 'docle-set-code',
        code: code
      }, '*');
    }
  }, [code]);

  // Build iframe URL
  const baseUrl = endpoint || (typeof window !== 'undefined' && (window as any).DOCLE_ENDPOINT) || 'https://app.docle.co';
  const params = new URLSearchParams({
    lang,
    theme,
    code,
    readonly: String(readonly),
    showOutput: String(showOutput),
    autorun: String(autorun)
  });

  // Add API key if provided
  if (apiKey) {
    params.set('apiKey', apiKey);
  }

  const src = `${baseUrl}/embed?${params}`;

  // Normalize height/width
  const normalizedHeight = typeof height === 'number' ? `${height}px` : height;
  const normalizedWidth = typeof width === 'number' ? `${width}px` : width;

  return (
    <div
      className={className}
      style={{
        width: normalizedWidth,
        height: normalizedHeight,
        ...style
      }}
    >
      <iframe
        ref={iframeRef}
        src={src}
        style={{
          width: '100%',
          height: '100%',
          border: 'none',
          borderRadius: '8px',
          display: 'block'
        }}
        allow="cross-origin-isolated"
        title="Docle Code Playground"
      />
    </div>
  );
}
